### ISSUE TITLE
upload images to CDN as part of the build / publish process

### ISSUE THREAD

**Issue by jexp** [neo4j-documentation/developer-guides#12]
We should still have all images in this repository (also for local rendering)

but as part of the build process upload them to the right place in the CDN

/cc @mneedham @ElaineRosenberg

**Comment by Mogztter** [comment]
Another solution is to use image resource ids: https://docs.antora.org/antora/2.3/page/image-resource-id-examples/

In this case, the images will be published by Antora.
Since the Intellij AsciiDoc plugin supports Antora image resource ids, the preview will also work.

**Comment by jexp** [comment]
I doubt that we want them to be published by antora? Would that mean being published to the static content?
Only if it would go to the same CDN?

But then I don't know about the lifetime of static assets like images vs. more dynamic ones (html/js/css) which change more frequently?

**Comment by Mogztter** [comment]
> I doubt that we want them to be published by antora? Would that mean being published to the static content?
Only if it would go to the same CDN?

Yes, I believe that we are currently publishing the documentation site (html, js, css, images) to Amazon S3?
I'm pretty sure that we can configure a more aggressive cache strategy on images based on the "path" and/or the file extension.

> But then I don't know about the lifetime of static assets like images vs. more dynamic ones (html/js/css) which change more frequently?

If you are using CloudFront it might also be possible to configure it to serve images directly from the edge cache.
